### ISSUE TITLE
How to remove a failed node completely?

### ISSUE THREAD

**Issue by gazoscalvertos** [robertsLando/Zwave2Mqtt#4]
Is there a way to remove a failed node?

I've tried modifying the xml file both while the server is up and down but doesn't make a difference. Can't see an option for it unless I'm missing something.

Thanks

**Comment by robertsLando** [comment]
Check Readme.md. In order to replace a failed node you firstly have to make the controller detect the node as failed, send `update return routes` action or `update neighbors` To the failed node, controller status should said "node failed" once done, now use the controller action `replace failed node` and the controller will turn on inclusion and will assign the replaced nodeid to the new node added

**Comment by gazoscalvertos** [comment]
Thanks, I should have read that first as I simply ploughed ahead and readded the nodes that fell out of sync. Now I have 2 nodeIDs which are effectively dead, so the only way to get shot of these is to wait until i have new devices to add?

**Comment by robertsLando** [comment]
@gazoscalvertos Yes. Actually some weired thing happens when removing devices in Openzwave, scan takes lot longer and all the systems seems to be slow down, If you have died nodes I suggest you to firstly exclude them from the controller. 

The best thing you can do is to exclude all devices, hard reset the controller and add all them back.
